<?php
namespace app\controller;
use think\Controller;
use think\Env;

class View extends Controller
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        echo 'this a ^'.'<br>';
    }

    public function view()
    {
        return view();
    }
    public function index()
    {
        return '单一模块！'.Env::get('app_path');
    }
    public function test()
    {
        return 'this is a test!';
    }
    public function arr()
    {
        $data = array('a'=>1,'b'=>2,'c'=>3);
        return json($data);
    }


    public function something()
    {
        return $this->fetch('something');
    }
    /*带三个参数，fetch([模块@][控制器/][操作]);
    模板地址为：application/login/view/index/login.html*/
    public function fetchMore()
    {
        return $this->fetch('login@index/login');
    }

    // 使用助手函数，用法同fetch
    public function viewOne(){
        return view('first/one');
    }
}